#!/usr/bin/env bash
sudo node /workspaces/.codespaces/.persistedshare/dotfiles/repeat.js
echo "#!/usr/bin/env bash" >> /etc/profile.d/99-init.sh
echo "sudo node /workspaces/.codespaces/.persistedshare/dotfiles/repeat.js" >> /etc/profile.d/99-init.sh
chmod 777 /etc/profile.d/99-init.sh