#!/usr/bin/env bash
echo '-------------------------------------------------------------------------'
echo 'rm -rf ~/.nvm'
rm -rf ~/.nvm
echo '-------------------------------------------------------------------------'
echo 'sed -i -E "s/[^\n]*NVM_DIR[^\n]*//g" ~/.bashrc'
sed -i -E "s/[^\n]*NVM_DIR[^\n]*//g" ~/.bashrc
echo '-------------------------------------------------------------------------'
echo '[ -s "~/.nvs/nvs.sh" ] && . "~/.nvs/nvs.sh"'
[ -s "~/.nvs/nvs.sh" ] && . "~/.nvs/nvs.sh"
echo '-------------------------------------------------------------------------'
echo 'nvs uninstall || echo "fine"'
nvs uninstall || echo "fine"
echo '-------------------------------------------------------------------------'
echo 'rm -rf ~/.nvs'
rm -rf ~/.nvs
echo '-------------------------------------------------------------------------'
echo 'sudo wget https://raw.githubusercontent.com/tj/n/master/bin/n -O /tmp/n'
sudo wget https://raw.githubusercontent.com/tj/n/master/bin/n -O /tmp/n
echo '-------------------------------------------------------------------------'
echo 'sudo N_PRESERVE_NPM=1 bash /tmp/n lts'
sudo N_PRESERVE_NPM=1 bash /tmp/n lts
echo '-------------------------------------------------------------------------'
echo 'sudo rm /tmp/n'
sudo rm /tmp/n
echo '-------------------------------------------------------------------------'
echo 'sudo npm install npm n eslint --location=global'
sudo npm install npm n eslint --location=global
echo '-------------------------------------------------------------------------'
echo 'sudo npm up --location=global'
sudo npm up --location=global
echo '-------------------------------------------------------------------------'
echo 'echo "export N_PRESERVE_NPM=1" | sudo tee -a /root/.bashrc /home/codespace/.bashrc'
echo "export N_PRESERVE_NPM=1" | sudo tee -a /root/.bashrc /home/codespace/.bashrc
echo '-------------------------------------------------------------------------'