name: Metrics
on:
  schedule:
    - cron: 0 */6 * * *
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/lowlighter-metrics.yaml
    branches:
      - master

concurrency:
  group: ${{ github.workflow_ref }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: AnnAngela
          template: classic

          # plugins/base
          base: header, activity, community, repositories, metadata
          base_indepth: true
          repositories_affiliations: owner, collaborator, organization_member
          commits_authoring: AnnAngela, naganjue@vip.qq.com, annangela@moegirl.org, 9762652+AnnAngela@users.noreply.github.com

          # plugins/core
          config_timezone: Asia/Shanghai
          optimize: css, xml, svg
          experimental_features: --optimize-svg
          use_prebuilt_image: yes
          notice_releases: yes
          verify: yes
          repositories_skipped: AnnAngela/annangela.cn-monitor
          quota_required_rest: 1000
          quota_required_graphql: 1000
          config_display: large

          # plugins/achievements
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C

          # plugins/habits
          plugin_habits: yes
          plugin_habits_from: 1000
          plugin_habits_days: 30
          plugin_habits_charts: yes
          plugin_habits_trim: yes
          plugin_habits_facts: yes
          plugin_habits_skipped: AnnAngela/annangela.cn-monitor

          # plugins/introduction
          plugin_introduction: yes
          plugin_introduction_title: yes

          # plugins/isocalendar
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          # plugins/languages
          plugin_languages: yes
          plugin_languages_skipped: AnnAngela/annangela.cn-monitor
          plugin_languages_sections: most-used
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_threshold: 0%

          # plugins/lines
          plugin_lines: yes
          plugin_lines_skipped: AnnAngela/annangela.cn-monitor
          plugin_lines_sections: base, repositories, history

          # plugins/notable
          plugin_notable: yes
          plugin_notable_skipped: AnnAngela/annangela.cn-monitor
          plugin_notable_from: all
          plugin_notable_repositories: yes
          plugin_notable_types: commit, pull_request
          plugin_notable_indepth: yes

          # plugins/topics
          plugin_topics: yes
          plugin_topics_limit: 15
          plugin_topics_mode: icons
          plugin_topics_sort: activity

          # plugins/traffic
          plugin_traffic: yes
          plugin_traffic_skipped: AnnAngela/annangela.cn-monitor
