name: stall-action
on:
  schedule:
    - cron: 0/30 * * * *
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  stall-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          show-progress: false
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          check-latest: true
          cache: npm
      - name: Installing the dependencies
        uses: AnnAngela/cached_node-modules@v1
      - name: Close stall action
        env:
          GITHUB_TOKEN: ${{ secrets.STALL_ACTION_KEY }}
        run: node stall-action.mjs
