on:
  workflow_dispatch

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          check-latest: true
          cache: npm
      - name: Install @actions/artifact@2.0.0
        run: |
          npm i @actions/artifact@2.0.0
      - name: Running test file
        run: |
          node test
