name: test

on:
  workflow_dispatch

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      matrix:
        os:
          - ubuntu-latest
          # - macos-latest
          # - windows-latest
    steps:
      - name: cat /proc/cpuinfo
        run:  cat /proc/cpuinfo
      - name: vmstat
        run:  vmstat
      - name: lscpu
        run:  lscpu
      - name: free -h
        run:  free -h
      - name: df -h
        run:  df -h
      - name: swapon --show
        run:  swapon --show
      - name: cat /proc/swaps
        run:  cat /proc/swaps
