name: test

on:
  workflow_dispatch:

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      matrix:
        os:
          # - ubuntu-latest
          - macos-latest
          # - windows-latest
    steps:
      - name: download
        env:
          TMPDIR: ${{ runner.temp }}
        run: |
          mkdir packages
          wget https://github.com/MaaAssistantArknights/MaaRelease/releases/download/v4.20.0/MAA-v4.20.0-macos-universal.dmg -O packages/MAA-v4.20.0-macos-universal.dmg
      - name: dylib
        run: |
          cd ${{ runner.temp }}
          mkdir -p macos-runtime-temp
          echo Attaching release package...
          hdiutil attach ${{ github.workspace }}/packages/MAA-v4.20.0-macos-universal.dmg
          echo ::group::Copying files...
          cp -v /Volumes/MAA/MAA.app/Contents/Frameworks/*.dylib macos-runtime-temp/
          cp -vr /Volumes/MAA/MAA.app/Contents/Resources/resource macos-runtime-temp/resource
          echo ::endgroup::
          echo ::group::Linking files...
          libonnxruntime_file=$(ls -1 macos-runtime-temp/libonnxruntime*.dylib)
          ln -vs $libonnxruntime_file macos-runtime-temp/libonnxruntime.dylib
          libopencv_world_file=$(ls -1 macos-runtime-temp/libopencv_world*.dylib)
          ln -vs $libopencv_world_file macos-runtime-temp/libopencv_world4.dylib
          echo ::endgroup::
          cd macos-runtime-temp
          echo ::group::Compressing files...
          zip -yrX9 ${{ github.workspace }}/packages/MAA-v4.20.0-macos-runtime-universal.zip *
          echo ::endgroup::
          echo Detaching release package...
          hdiutil detach /Volumes/MAA
      - name: result
        run: |
          echo packages:
          ls -lh packages
          echo ::group::macos-runtime-universal.zip:
          unzip -l packages/MAA-v4.20.0-macos-runtime-universal.zip
          echo ::endgroup::
          echo Original size:
          du -hs ${{ runner.temp }}/macos-runtime-temp
          echo Compressed size:
          ls -lh packages/MAA-v4.20.0-macos-runtime-universal.zip
