name: test

on:
  workflow_dispatch:

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      matrix:
        os:
          # - ubuntu-latest
          - macos-latest
          # - windows-latest
    steps:
      - name: download
        env:
          TMPDIR: ${{ runner.temp }}
        run: |
          wget https://github.com/MaaAssistantArknights/MaaRelease/releases/download/v4.20.0-beta.3/MAA-v4.20.0-beta.3-macos-universal.dmg
          hdiutil attach MAA-v4.20.0-beta.3-macos-universal.dmg
      - name: ls /Volumes
        run: ls /Volumes
      - name: dylib
        run: |
          mkdir -p ${{ runner.temp }}/dylib
          cp /Volumes/MAA/MAA.app/Contents/Frameworks/*.dylib ${{ runner.temp }}/dylib
          ls -lh ${{ runner.temp }}/dylib
          du -hs ${{ runner.temp }}/dylib
          zip -X9 MAA-${{ needs.create-tag.outputs.release_tag }}-macos-runtime-universal.zip ${{ runner.temp }}/dylib/*
          ls -lh MAA-${{ needs.create-tag.outputs.release_tag }}-macos-runtime-universal.zip
