name: test

on:
  workflow_dispatch:

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    steps:
      - name: tmpfile=$(mktemp)
        env:
          TMPDIR: ${{ runner.temp }}
        run: |
          tmpfile=$(mktemp)
          echo $tmpfile
