name: test

on:
  workflow_dispatch:

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      matrix:
        os:
          # - ubuntu-latest
          - macos-latest
          # - windows-latest
    steps:
      - name: download
        env:
          TMPDIR: ${{ runner.temp }}
        run: |
          wget https://github.com/MaaAssistantArknights/MaaRelease/releases/download/v4.20.0/MAA-v4.20.0-macos-universal.dmg -O packages/MAA-v4.20.0-macos-universal.dmg
      - name: dylib
        run: |
          cd ${{ runner.temp }}
          mkdir -p macos-runtime-temp
          hdiutil attach ${{ github.workspace }}/packages/MAA-v4.20.0-macos-universal.dmg
          cp /Volumes/MAA/MAA.app/Contents/Frameworks/*.dylib macos-runtime-temp/
          cp -r /Volumes/MAA/MAA.app/Contents/Resources/resource macos-runtime-temp/resource
          ln -s macos-runtime-temp/libonnxruntime.1.14.1.dylib macos-runtime-temp/libonnxruntime.dylib
          ln -s macos-runtime-temp/libopencv_world4.407.dylib macos-runtime-temp/libopencv_world4.dylib
          zip -rX9 ${{ github.workspace }}/packages/MAA-v4.20.0-macos-runtime-universal.zip macos-runtime-temp/*
          hdiutil detach /Volumes/MAA
      - name: result
        run: |
          ls -l packages
          unzip -l packages/MAA-v4.20.0-macos-runtime-universal.zip
