name: test

on:
  workflow_dispatch

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  test:
    name: Test script
    runs-on: ubuntu-latest
    steps:
      # https://github.com/marketplace/actions/github-script
      - uses: actions/github-script@v7
        with:
          script: |
            console.log(context)
