name: test

on:
  workflow_dispatch

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      matrix:
        os:
          # - ubuntu-latest
          # - macos-latest
          - windows-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout arkntools/data-downloader
        with:
          show-progress: false
          repository: arkntools/data-downloader
          ref: dist
          path: ./arkntools-data-downloader
          token: ${{ secrets.ARKNTOOLS_MAA_RESOURCE_UPDATER }}
      - name: Download txwy game data
        uses: ./arkntools-data-downloader
        with:
          cmd: downloadExcel
          save-path: ${{ runner.temp }}/data
          # 要下载哪些服务器的 (cn, us, jp, kr, tw)，如果全下载就不用加这个参数，默认全下载
          servers: |
            tw
          # 每个服对应的 fbs commit - https://github.com/MooncellWiki/OpenArknightsFBS
          # 这个需要自己维护，因为外服跟国服版本号不一样所以没找到高效的自动化的办法
          # 不下载的 server 可以不写，国服不用写因为必定用的是最新的
          # fbs-heads: |
          #   tw: 324260f
          # 要下载的文件，目前只能下载 excel 里的，如果需要下载 excel 外的文件再跟我说吧
          excel-files: |
            roguelike_topic_table
            item_table
            building_data
            gacha_table
            character_table
            activity_table
      - name: Copy txwy game data
        run: mkdir -p ./tools/ResourceUpdater/ArknightsGameData_Yostar && mv ${{ runner.temp }}/data/tw/excel/* ./tools/ResourceUpdater/ArknightsGameData_Yostar
      - name: tree -F ${{ runner.temp }}/data
        run: tree -F ${{ runner.temp }}/data
      - name: tree -F ./tools/ResourceUpdater/ArknightsGameData_Yostar
        run: tree -F ./tools/ResourceUpdater/ArknightsGameData_Yostar
