name: test

on:
  workflow_dispatch

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      matrix:
        os:
          - ubuntu-latest
          # - macos-latest
          # - windows-latest
    steps:
      - uses: actions/checkout@v4
        name: step1
        with:
          show-progress: false
          repository: JakeChampion/polyfill-service
          path: step1
          sparse-checkout: |
            polyfill-libraries/3.111.0*
          sparse-checkout-cone-mode: false
      - name: result
        run: |
          tree -L 4 .
