name: test

on:
  workflow_dispatch

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    container: ubuntu:22.04
    steps:
      - name: add repo
        run: |
          apt-get update
          DEBIAN_FRONTEND=noninteractive apt-get install software-properties-common -y
          DEBIAN_FRONTEND=noninteractive add-apt-repository ppa:ondrej/php
          apt-get update
      - name: show php-fpm dependencies
        run: |
          apt-cache depends php-fpm
      - name: show php-redis dependencies
        run: |
          apt-cache depends php-redis
